# name: "PR Link Checker"
# on:
#   pull_request:
#     types: [opened, edited, synchronized]

# jobs:
#   check-link:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check for linked issue
#         uses: hattan/verify-linked-issue-action@v1.1.5
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           message: "Please link an issue to this PR"
true